name: docker release

on:
  push:
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
  # # Run tests for any PRs.
  # pull_request:

env:
  OAUTH2_PROXY_TAG: v7.7.1

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Setup buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Push image
        run: |
          # change the version

          docker buildx build \
            --build-arg OAUTH2_PROXY_TAG=${OAUTH2_PROXY_TAG}
            --tag nxest/oauth2-proxy-auto-sign-in:${OAUTH2_PROXY_TAG} \
            --tag nxest/oauth2-proxy-auto-sign-in:lastest \
            --platform linux/amd64,linux/arm64 \
            src/main/docker/oauth2-proxy-auto-sign-in \
            --push
