name: sync images to docker.io

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  sync-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: hhyasdf/image-sync-action@v1.1
        with:
          auth_file: ./image-sync/auth.yaml
          images_file: ./image-sync/images.yaml
          version: latest
          proc: 10
        env:
          DOCKER_IO_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_IO_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

